name: Test GitHub Action
on: [push]
jobs:
  test-GitHub-Action:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: npm install
        run: npm install
      - name: compile TS code
        run: npm run compile
      - name: Test Action
        id: run-gh-action
        uses: ./