name: Test GitHub Action
on: [pull_request]
jobs:
  test-GitHub-Action:
    name: Execute GitHub Action
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: npm install
        run: npm install
      - name: compile TS code
        run: npm run compile
      - name: Test Action
        id: run-gh-action
        uses: ./
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
  execute-UT:
    name: Execute UT
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: npm install
        run: npm install
      - name: Execute UT
        run: npm run test